services:
  - type: web
    name: pgadmin
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: biomedlink96@gmail.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: NzamSim6969?
